### ISSUE TITLE
提一些性能上的建议

### ISSUE THREAD

**Issue by robxyy** [Tourbillon/Android-Routine#6]
- [ ] 异步创建 Navigator ⚡️ （接入RxJava? 开发者自己控制 :shipit:  ）
- [ ] 切换到编译时 🗡

若有切换页面动画，那就棒了

**Comment by Coolerfall** [comment]
- 只是跳转，接入rxjava似乎没有太大必要，这个基本是主线程执行，待考虑

- 切换到编译时不太现实，动态注册scheme之后，需要运行时去匹配

- 动画后续添加
